# Generated by Django 3.2.6 on 2022-01-12 14:53

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='profile/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
