# Generated by Django 3.2.6 on 2022-01-13 08:05

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220112_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='profile/', verbose_name='Image'),
        ),
    ]
