# Generated by Django 3.2.6 on 2022-01-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='main',
            new_name='default',
        ),
    ]
