# Generated by Django 3.2.6 on 2022-01-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220102_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='productdetail',
            unique_together={('key', 'product')},
        ),
        migrations.CreateModel(
            name='XImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product')),
                ('default', models.BooleanField(default=False)),
                ('x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.x')),
            ],
        ),
    ]
